/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  ipWhitelist: [],
  modules: [
    {
      module: 'alert',
      config: {},
      header: ''
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {}
    },
    {
      module: 'clock',
      position: 'top_left',
      header: '',
      config: {}
    },
	    {
      module: 'todolist',
      position: 'top_left',
      header: '',
      config: {}
    },
    {
      module: 'recom',
      position: 'bottom_bar',
      header: '',
      config: {}
    },
    {
      module: 'calendar',
      header: 'Calendar',
      position: 'top_left',
      config: {
        calendars: [
          {
            symbol: 'calendar-check',
            url: 'webcal://1.15.22.18:8080/test.ics'
          }
        ]
      }
    },
    {
      module: 'compliments',
      position: 'lower_third',
      config: {}
    },
    {
      module: 'weather',
      position: 'top_right',
      config: {
        location: '郑州',
        locationID: '1784658',
        apiKey: 'a711126a54a4a77ed054990061372a3e'
      }
    },
    {
      module: 'MMM-Remote-Control',
      position: 'bottom_bar',
      config: {
        showModuleApiMenu: true,
        secureEndpoints: true
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: 'Weather Forecast',
      config: {
        type: 'forecast',
        location: '南京',
        locationID: '1799962',
        apiKey: 'a711126a54a4a77ed054990061372a3e'
      }
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: '人民网——世界',
            url: 'http://www.people.com.cn/rss/world.xml'
          },
          {
            title: '人民网——时政',
            url: 'http://www.people.com.cn/rss/politics.xml'
          },
        ]
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  locale: 'en-US'
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
